stages:
  - install
  - build
  - deploy

install_dependencies:
  stage: install
  image: node:20
  script:
    - node -v
    - echo "Installing dependencies"
    - npm install
  cache:
    paths:
      - node_modules/

build_app:
  stage: build
  image: node:20
  script:
    - echo "Building Instructor Application"
    - node -v
    - npm -v
    - npm i  # Use 'npm ci' instead of 'npm install' for CI environments
    - CI=false npm run build --verbose
  artifacts:
    paths:
      - build
  dependencies:
    - install_dependencies

deploy_to_aws:
  stage: deploy
  image: node:20
  script:
    - echo "Deploying to AWS EC2"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/agtech.pem
    - chmod 400 ~/.ssh/agtech.pem
    - ssh-keyscan -H $AWS_SSH_IP >> ~/.ssh/known_hosts
    - rsync -avz -e "ssh -i ~/.ssh/agtech.pem" build/* $AWS_SSH_USER@$AWS_SSH_IP:/home/ubuntu/app/instructor
  dependencies:
    - install_dependencies    

